name: K3S Runner Test
on: [push, workflow_dispatch]

jobs:
  test-job:
    # 중요: helm install 시 설정한 runner scale set 이름을 적어줍니다
    runs-on: my-k3s-runner
    steps:
      - name: Hello from k3s
        run: |
          echo "Hello! This job is running on my local k3s cluster."
          hostname